[package]
name = "day-4"
version = "0.1.0"
authors = [ "Cowboylaserkittenjetshark@cblkjs.com" ]
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
regex = "1.11.1"
